version: 666.{build}
skip_tags: false
os: Visual Studio 2017
clone_depth: 1
clone_folder: C:\textosaurus

environment:
  access_token:
    secure: oR2iY1h+Z5AF4t3yP1mxNW7HL8qhPm8y4Uupp4b03QSC7puVrkkCaO1E1NQA9q9K

artifacts:
  - path: 'textosaurus-build\src\textosaurus\*win64.exe'
    name: textosaurusexe

  - path: 'textosaurus-build\src\textosaurus\*win64.7z'
    name: textosaurus7z

deploy:
  description: 'New Textosaurus release.'
  provider: GitHub
  auth_token:
    secure: oR2iY1h+Z5AF4t3yP1mxNW7HL8qhPm8y4Uupp4b03QSC7puVrkkCaO1E1NQA9q9K
  artifact: textosaurusexe, textosaurus7z
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
    
build_script:
  - git submodule update --init --recursive
  - ps: C:\textosaurus\resources\scripts\.appveyor-prepare-win.ps1
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - ps: C:\textosaurus\resources\scripts\.appveyor-build-win.ps1

on_success:
  - ps: C:\textosaurus\resources\scripts\.appveyor-install-win.ps1