version: 666.{build}
skip_tags: false
os: Visual Studio 2017
clone_depth: 1
clone_folder: C:\textilosaurus

environment:
  access_token:
    secure: bM8uJbH7GK+2EW6aL8D0/qwwdM/lzW6y2odXWs/VcMq+nUBZa68x+k3EpZEAo6iT

artifacts:
  - path: 'textilosaurus-build\*win64.exe'
    name: textilosaurusexe

  - path: 'textilosaurus-build\*win64.7z'
    name: textilosaurus7z

deploy:
  description: 'New Textilosaurus release.'
  provider: GitHub
  auth_token:
    secure: XCWdr9wPgK4gm6289WXCg2vtMA02eBSnj6eKHC+ps6Z5lgw0jsK09UQ5y9E9ZFwS
  artifact: textilosaurusexe, textilosaurus7z
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
    
build_script:
  - git submodule update --init --recursive
  - ps: C:\textilosaurus\resources\scripts\.appveyor-prepare-win.ps1
  - set "PATH=C:\textilosaurus\qt-5.10-static-msvc2017-ltcg-x86_64\bin;%PATH%"
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - cd C:\textilosaurus
  - mkdir textilosaurus-build
  - cd textilosaurus-build
  - dir
  - C:\textilosaurus\qt-5.10-static-msvc2017-ltcg-x86_64\bin\qmake.exe C:\textilosaurus\textilosaurus.pro -r CONFIG+=release
  - C:\textilosaurus\resources\scripts\findreplace\findreplace.exe " qjp2.lib" " " "C:\textilosaurus\textilosaurus-build\Makefile" > "C:\textilosaurus\textilosaurus-build\Makefile"
  - nmake
  - nmake windows_all


on_success:
  - ps: C:\textilosaurus\resources\scripts\.appveyor-install-win.ps1
