version: 666.{build}
skip_tags: false
os: Visual Studio 2017
clone_depth: 1
clone_folder: C:\textilosaurus

environment:
  QTDIR: 'C:\msys64\mingw64\share\qt5'
  QMAKESPEC: win32-g++
  COMPILERBAT: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  access_token:
    secure: bM8uJbH7GK+2EW6aL8D0/qwwdM/lzW6y2odXWs/VcMq+nUBZa68x+k3EpZEAo6iT

artifacts:
  - path: 'textilosaurus-build\*win64.exe'
    name: textilosaurusexe

  - path: 'textilosaurus-build\*win64.7z'
    name: textilosaurus7z

deploy:
  description: 'New Textilosaurus release.'
  provider: GitHub
  auth_token:
    secure: XCWdr9wPgK4gm6289WXCg2vtMA02eBSnj6eKHC+ps6Z5lgw0jsK09UQ5y9E9ZFwS
  artifact: textilosaurusexe, textilosaurus7z
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
    
build_script:
  - git submodule update --init --recursive
  - C:\msys64\usr\bin\bash.exe --login "C:\textilosaurus\resources\scripts\.appveyor-prepare-win.sh"
  - C:\msys64\usr\bin\bash.exe --login "C:\textilosaurus\resources\scripts\.appveyor-build-win.sh"

on_success:
  - ps: .\..\resources\scripts\.appveyor-install-win.ps1