version: 666.{build}
skip_tags: false
os: Visual Studio 2017
clone_depth: 1
clone_folder: C:\textilosaurus

environment:
  QTDIR: 'C:\Qt\5.9\msvc2017_64'
  QMAKESPEC: win32-msvc
  COMPILERBAT: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  access_token:
    secure: bM8uJbH7GK+2EW6aL8D0/qwwdM/lzW6y2odXWs/VcMq+nUBZa68x+k3EpZEAo6iT

artifacts:
  - path: 'textilosaurus-build\*win64.exe'
    name: textilosaurusexe

  - path: 'textilosaurus-build\*win64.7z'
    name: textilosaurus7z

deploy:
  description: 'New Textilosaurus release.'
  provider: GitHub
  auth_token:
    secure: XCWdr9wPgK4gm6289WXCg2vtMA02eBSnj6eKHC+ps6Z5lgw0jsK09UQ5y9E9ZFwS # your encrypted token from GitHub
  artifact: textilosaurusexe, textilosaurus7z # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
    
build_script:
  - git submodule update --init --recursive
  - set "QT_PLUGIN_PATH=%QTDIR%\plugins"
  - set "PATH=%QTDIR%\bin;%PATH%"
  - '%COMPILERBAT%'
  - dir
  - mkdir textilosaurus-build
  - cd textilosaurus-build
  - lrelease.exe -compress C:\textilosaurus\textilosaurus.pro
  - qmake.exe C:\textilosaurus\textilosaurus.pro
  - nmake
  - nmake windows_all

on_success:
  - ps: .\..\resources\scripts\.appveyor-install-win.ps1